CREATE TABLE IF NOT EXISTS educational_direction (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    group_name VARCHAR(255) NOT NULL,
    count_budget INT NOT NULL,
    count_contact INT NOT NULL,
    price INT NOT NULL,
    subject1 VARCHAR(255) NOT NULL,
    subject2 VARCHAR(255) NOT NULL,
    subject3 VARCHAR(255) NOT NULL,
    value1 INT NOT NULL,
    value2 INT NOT NULL,
    value3 INT NOT NULL,
    sum INT NOT NULL,
    competive_b float NOT NULL,
    competive_k float NOT NULL
);